"""
backend.py - The part that does the work.
Copyright (C) <2020>  <Adoria298>

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/>.

----
"""
# imports
## pip
import grpc
## homemade
### generated by protoc
from uno_pb2 import Player
import uno_pb2_grpc

class Backend():
    def __init__(self, channel, player_name):
        self.stub = uno_pb2_grpc.UnoStub(channel)
        self.me = Player(name=player_name, hand=[], uno_declared=False, score=0)
        self.add_me_to_game()
        self.state = self.stub.RequestStateOfPlay(self.me)
    
    def add_me_to_game(self):
        try:
            self.stub.AddPlayer(self.me)
        except grpc.RpcError as e:
            if e.code() == grpc.StatusCode.INTERNAL:
                if e.details() in ("UNKNOWN", "TOO_MANY_PLAYERS", "NAME_TAKEN"):
                    raise ValueError(e.details())
                else:
                    raise e
            else:
                raise e